### ISSUE TITLE
Error of access - Module: Restricted administration rights

### ISSUE THREAD

**Issue by kurkop** [yelizariev/access-addons#15]
I have a problem with the module restricted administration rights, I think that it's a regression. 
This error appaer in user menu and inventory settings (I believe that in other views).

```
Invalid view definition

Error details:
Field `sel_groups_11` does not exist

Error context:
View `res.users.groups`
[view_id: 152, xml_id: base.user_groups_view, model: res.users, parent_id: 149] 
```
![screenshot-localhost 2016-03-30 21-55-54](https://cloud.githubusercontent.com/assets/2367831/14164137/4a097492-f6c2-11e5-819c-9823e43b9b45.png)

**Comment by yelizariev** [comment]
I guess you use 9.0 version

It could be related: https://github.com/yelizariev/access-addons/pull/3

Could you provide steps to reproduce?

**Comment by kurkop** [comment]
I guess you use 9.0 version
- Yes.

It could be related: #3
- Yes, It seems to be the same message.

Could you provide steps to reproduce?
- Create a new database
- Install access_restricted
- Create a new user with "settings" permissions
- Login with the new user
- Try access to settings->users->click to one user (here fails)

I have the lastest commit of access-addons code.

**Comment by yelizariev** [comment]
I think I found the reason: https://github.com/odoo/odoo/commit/40a299c580c4608edab8781fda4e66f39611543b
