### ISSUE TITLE
Access restrict not expected - Module: Restricted administration rights

### ISSUE THREAD

**Issue by kurkop** [yelizariev/access-addons#17]
I have a access restricted when a user admin (not superuser) want "Apply" changes in settings of inventory or accounting modules (maybe others).

```
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n
```

I'm testing the module and comment this rule and works correctly.
https://github.com/yelizariev/access-addons/blob/9.0/access_restricted/security.xml#L16

Steps to reproduce:
- Create a new database with inventory and accounting apps. Install access_restricted module.
- Create a new user with "settings" permissions
- Login with the new user
- Access to Accounting->settings: change configuration and click in "Apply" button.

**Comment by yelizariev** [comment]
@kurkop 
I found that odoo tries to update Technical Settings group. I think granting access to this group to everybody should fix the problem

**Comment by yelizariev** [comment]
The commit partly fix the issue. 
The problem that Settings page do exactly what the module restrict -- they try to update groups

**Comment by kurkop** [comment]
Ok, this commit allows to write, but the message continues to appear.

**Comment by yelizariev** [comment]
It allows to write in "Technical settngs" only. While Account\Inventory Settings page tries to write on other groups, e.g. "Manage packages"

**Comment by kurkop** [comment]
I found other groups, group_erp_manager, group_configuration, Could this work?

**Comment by yelizariev** [comment]
I have and idea how to make Settings pages work. There will be no error, but checkboxes that works with groups will not take affect after clicking Apply.
Wait for updates.

**Comment by yelizariev** [comment]
done in #18
