### ISSUE TITLE
Users can write messages to superuser in mail module.

### ISSUE THREAD

**Issue by blaggacao** [yelizariev/access-addons#7]
Hi, we noticed, that normal users can write messages to the admin user. We use the admin user for data maintainance. In the eye of the customer it shouldn't exist at all. See attached screenshots (bottom line in the message module):
<img width="227" alt="capture" src="https://cloud.githubusercontent.com/assets/7548295/13852390/ccbcedd0-ec2f-11e5-9656-1636c145e8f3.PNG">

**Comment by yelizariev** [comment]
fixed.
